name: Android Build & Release

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
        
    - name: Create keystores directory
      run: mkdir -p android/app/keystores
        
    - name: Setup Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystores/upload-keystore.keystore
        
    - name: Create gradle.properties
      run: |
        echo "MYAPP_UPLOAD_STORE_FILE=keystores/upload-keystore.keystore" >> android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> android/gradle.properties
        echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> android/gradle.properties
        
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Clean Gradle
      run: |
        cd android
        ./gradlew clean
        
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon --stacktrace
      
    - name: Build AAB
      run: |
        cd android
        ./gradlew bundleRelease --no-daemon --stacktrace
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
